<?php

declare(strict_types=1);

/*
 * Klartexte der Warn-/Alarmcodes der Hoymiles Wechselrichter.
 *
 * Quelle: ioBroker.hoymiles (https://github.com/Eistee82/ioBroker.hoymiles)
 * src/lib/alarmCodes.ts und src/lib/alarmCodesData.ts
 * MIT License, Copyright (c) Eistee82
 * Die Texte stammen dort aus dem Hoymiles-Cloud-Wörterbuch (mwc) und der warn_code.json der S-Miles App.
 */

namespace Hoymiles\DTU{
    class WarnCodes
    {
        /**
         * Code => [Englisch, Deutsch]
         */
        public const Texts = [
            1     => ['Reset', 'Neustart'],
            2     => ['Time calibration', 'Zeitkalibrierung'],
            3     => ['EEPROM reading and writing error during operation', 'EEPROM Lese-/Schreibfehler während des Betriebs'],
            4     => ['Offline', 'Offline'],
            11    => ['Grid voltage surge', 'Netzspannungsstoß'],
            12    => ['Grid voltage sharp drop', 'Starker Netzspannungsabfall'],
            13    => ['Grid frequency mutation', 'Sprunghafte Netzfrequenzänderung'],
            14    => ['Grid phase mutation', 'Sprunghafte Netzphasenänderung'],
            15    => ['Grid transient fluctuation', 'Transiente Netzschwankung'],
            36    => ['INV overvoltage or overcurrent', 'Wechselrichter Überspannung oder Überstrom'],
            38    => ['Insufficient input power (shutting down)', 'Eingangsleistung zu gering (Abschaltung)'],
            46    => ['FB overvoltage', 'FB Überspannung'],
            47    => ['FB overcurrent', 'FB Überstrom'],
            48    => ['FB clamp overvoltage', 'FB-Klemmung Überspannung'],
            49    => ['FB clamp overvoltage', 'FB-Klemmung Überspannung'],
            61    => ['Calibration parameter error', 'Kalibrierungsparameter fehlerhaft'],
            62    => ['System configuration parameter error', 'Systemkonfigurationsparameter fehlerhaft'],
            63    => ['Abnormal power generation data', 'Abnormale Stromerzeugungsdaten'],
            71    => ['VW function enable (grid overvoltage power reduction)', 'VW-Funktion aktiv (Leistungsreduzierung bei Netzüberspannung)'],
            72    => ['FW function enable (grid overfrequency power reduction)', 'FW-Funktion aktiv (Leistungsreduzierung bei Netzüberfrequenz)'],
            73    => ['TW function enable (over-temperature power reduction)', 'TW-Funktion aktiv (Leistungsreduzierung bei Übertemperatur)'],
            95    => ['PV1 module in suspected shadow', 'PV1-Modul vermutlich verschattet'],
            96    => ['PV2 module in suspected shadow', 'PV2-Modul vermutlich verschattet'],
            97    => ['PV3 module in suspected shadow', 'PV3-Modul vermutlich verschattet'],
            98    => ['PV4 module in suspected shadow', 'PV4-Modul vermutlich verschattet'],
            121   => ['Over temperature protection', 'Übertemperaturschutz'],
            122   => ['Locked by anti-theft lock', 'Durch Diebstahlsicherung gesperrt'],
            123   => ['Standby mode enabled by remote control', 'Standby-Modus per Fernbedienung aktiviert'],
            124   => ['Shut down by remote control', 'Ferngesteuert abgeschaltet'],
            125   => ['Grid configuration parameter error', 'Parameterfehler bei der Konfiguration des Elektrizitätsnetzes'],
            126   => ['EEPROM reading and writing error', 'EEPROM Lese-/Schreibfehler'],
            127   => ['Firmware error', 'Firmwarefehler'],
            128   => ['Hardware configuration information error', 'Fehler in der Hardware-Konfigurationsinformation'],
            129   => ['Abnormal bias', 'Abnormaler Trend'],
            130   => ['Offline', 'Offline'],
            141   => ['Grid overvoltage', 'Netzüberspannung'],
            142   => ['Grid overvoltage (10 min mean value)', 'Netzüberspannung (10-min. Mittelwert)'],
            143   => ['Grid undervoltage', 'Netzunterspannung'],
            144   => ['Grid overfrequency', 'Netzüberfrequenz'],
            145   => ['Grid underfrequency', 'Netzunterfrequenz'],
            146   => ['High RoCoF', 'Hohe RoCoF'],
            147   => ['No voltage on grid port', 'Keine Spannung am Netzanschluss'],
            148   => ['Grid disconnection', 'Netztrennung'],
            149   => ['Island detected', 'Inselbetrieb festgestellt'],
            150   => ['DCI exceeded', 'DC-Anteil überschritten'],
            151   => ['Severe grid wave distortion', 'Starke Netzwellenverzerrung'],
            181   => ['Abnormal insulation impedance', 'Abnormale Isolationsimpedanz'],
            182   => ['Abnormal grounding', 'Abnormale Erdung'],
            183   => ['Abnormal Relay', 'Anormales Relais'],
            184   => ['Abnormal Input Paralleling Wiring', 'Anormale Eingangs-Parallelverkabelung'],
            205   => ['MPPT-A input overvoltage', 'Eingangsüberspannung bei MPPT-A'],
            206   => ['MPPT-B input overvoltage', 'Eingangsüberspannung bei MPPT-B'],
            207   => ['MPPT-A input undervoltage', 'Eingangsunterspannung bei MPPT-A'],
            208   => ['MPPT-B input undervoltage', 'Eingangsunterspannung bei MPPT-B'],
            209   => ['PV1 no input', 'PV1 ohne Eingang'],
            210   => ['PV2 no input', 'PV2 ohne Eingang'],
            211   => ['PV3 no input', 'PV3 ohne Eingang'],
            212   => ['PV4 no input', 'PV4 ohne Eingang'],
            213   => ['PV1 & PV2 abnormal wiring', 'Verdrahtungsfehler bei PV1 und PV2'],
            214   => ['PV3 & PV4 abnormal wiring', 'Verdrahtungsfehler bei PV3 und PV4'],
            215   => ['PV1 input overvoltage', 'Eingangsüberspannung bei PV1'],
            216   => ['PV1 input undervoltage', 'Eingangsunterspannung bei PV1'],
            217   => ['PV2 input overvoltage', 'Eingangsüberspannung bei PV2'],
            218   => ['PV2 input undervoltage', 'Eingangsunterspannung bei PV2'],
            219   => ['PV3 input overvoltage', 'Eingangsüberspannung bei PV3'],
            220   => ['PV3 input undervoltage', 'Eingangsunterspannung bei PV3'],
            221   => ['PV4 input overvoltage', 'Eingangsüberspannung bei PV4'],
            222   => ['PV4 input undervoltage', 'Eingangsunterspannung bei PV4'],
            229   => ['Relay inner side Overvoltage', 'Überspannung an Relais-Innenseite'],
            231   => ['PV1 Arcing Fault', 'PV1 Störlichtbogen'],
            232   => ['PV2 Arcing Fault', 'PV2 Störlichtbogen'],
            233   => ['PV3 Arcing Fault', 'PV3 Störlichtbogen'],
            234   => ['PV4 Arcing Fault', 'PV4 Störlichtbogen'],
            301   => ['Hardware error Code 301', 'Hardwarefehlercode 301'],
            302   => ['Hardware error Code 302', 'Hardwarefehlercode 302'],
            303   => ['Hardware error Code 303', 'Hardwarefehlercode 303'],
            304   => ['Hardware error Code 304', 'Hardwarefehlercode 304'],
            305   => ['Hardware error Code 305', 'Hardwarefehlercode 305'],
            306   => ['Hardware error Code 306', 'Hardwarefehlercode 306'],
            307   => ['Hardware error Code 307', 'Hardwarefehlercode 307'],
            308   => ['Hardware error Code 308', 'Hardwarefehlercode 308'],
            309   => ['Hardware error Code 309', 'Hardwarefehlercode 309'],
            310   => ['Hardware error Code 310', 'Hardwarefehlercode 310'],
            311   => ['Hardware error Code 311', 'Hardwarefehlercode 311'],
            312   => ['Hardware error Code 312', 'Hardwarefehlercode 312'],
            313   => ['Hardware error Code 313', 'Hardwarefehlercode 313'],
            314   => ['Hardware error Code 314', 'Hardwarefehlercode 314'],
            316   => ['BOOSTA internal short circuit failure', 'BOOSTA interner Kurzschlussfehler'],
            317   => ['BOOSTB internal short circuit failure', 'BOOSTB interner Kurzschlussfehler'],
            318   => ['BOOSTA overcurrent protection failure', 'Ausfall des BOOSTA-Überstromschutzes'],
            319   => ['BOOSTB overcurrent protection failure', 'Ausfall des BOOSTB-Überstromschutzes'],
            320   => ['BOOSTC internal short circuit failure', 'BOOSTC interner Kurzschlussfehler'],
            321   => ['BOOSTD internal short circuit failure', 'BOOSTD interner Kurzschlussfehler'],
            322   => ['BOOSTC overcurrent protection failure', 'Ausfall des BOOSTC-Überstromschutzes'],
            323   => ['BOOSTD overcurrent protection failure', 'Ausfall des BOOSTD-Überstromschutzes'],
            324   => ['Arcing Lock-Up', 'Sperrlichtbogen'],
            420   => ['Abnormal master-slave communication', 'Anormale Master-Slave-Kommunikation'],
            421   => ['Abnormal master-slave communication', 'Anormale Master-Slave-Kommunikation'],
            422   => ['Abnormal master-slave communication', 'Anormale Master-Slave-Kommunikation'],
            423   => ['Abnormal master-slave communication', 'Anormale Master-Slave-Kommunikation'],
            424   => ['Abnormal master-slave communication', 'Anormale Master-Slave-Kommunikation'],
            1111  => ['Repeater', 'Repeater'],
            2000  => ['Standby', 'Standby'],
            2001  => ['Standby', 'Standby'],
            2002  => ['Standby', 'Standby'],
            2003  => ['Standby', 'Standby'],
            2004  => ['Standby', 'Standby'],
            3001  => ['Reset', 'Neustart'],
            3002  => ['Reset', 'Neustart'],
            3003  => ['Reset', 'Neustart'],
            3004  => ['Reset', 'Neustart'],
            5011  => ['PV1 MOSFET overcurrent', 'PV1 MOSFET Überstrom'],
            5012  => ['PV2 MOSFET overcurrent', 'PV2 MOSFET Überstrom'],
            5013  => ['PV3 MOSFET overcurrent', 'PV3 MOSFET Überstrom'],
            5014  => ['PV4 MOSFET overcurrent', 'PV4 MOSFET Überstrom'],
            5020  => ['H-bridge MOSFET overcurrent or overvoltage', 'H-Brücke MOSFET Überstrom oder Überspannung'],
            5041  => ['PV1 input overcurrent', 'PV1 Eingangsstrom zu hoch'],
            5042  => ['PV2 input overcurrent', 'PV2 Eingangsstrom zu hoch'],
            5043  => ['PV3 input overcurrent', 'PV3 Eingangsstrom zu hoch'],
            5044  => ['PV4 input overcurrent', 'PV4 Eingangsstrom zu hoch'],
            5051  => ['PV1 input overvoltage/undervoltage', 'Eingangsüberspannung/-unterspannung an PV1'],
            5052  => ['PV2 input overvoltage/undervoltage', 'Eingangsüberspannung/-unterspannung an PV2'],
            5053  => ['PV3 input overvoltage/undervoltage', 'Eingangsüberspannung/-unterspannung an PV3'],
            5054  => ['PV4 input overvoltage/undervoltage', 'Eingangsüberspannung/-unterspannung an PV4'],
            5060  => ['Abnormal bias', 'Abnormale Vorspannung'],
            5070  => ['Over temperature protection', 'Übertemperaturschutz'],
            5080  => ['Grid overvoltage/undervoltage', 'Netzüberspannung/-unterspannung'],
            5090  => ['Grid overfrequency/underfrequency', 'Netzüberfrequenz/-unterfrequenz'],
            5100  => ['Island detected', 'Inselbetrieb festgestellt'],
            5110  => ['GFDI failure', 'GFDI-Fehler'],
            5120  => ['Error Code 12', 'Fehlercode 12'],
            5141  => ['FB clamp overvoltage', 'FB-Klemmung Überspannung'],
            5142  => ['FB clamp overvoltage', 'FB-Klemmung Überspannung'],
            5143  => ['FB clamp overvoltage', 'FB-Klemmung Überspannung'],
            5144  => ['FB clamp overvoltage', 'FB-Klemmung Überspannung'],
            5150  => ['Grid overvoltage (10 min mean value)', 'Netzüberspannung (10-min. Mittelwert)'],
            5160  => ['Grid transient fluctuation', 'Transiente Netzschwankung'],
            5200  => ['Firmware error', 'Firmwarefehler'],
            5511  => ['Error Code 01', 'Fehlercode 01'],
            5512  => ['Error Code 01', 'Fehlercode 01'],
            5513  => ['Error Code 01', 'Fehlercode 01'],
            5514  => ['Error Code 01', 'Fehlercode 01'],
            5520  => ['Error Code 02', 'Fehlercode 02'],
            8310  => ['Shut down by remote control', 'Durch Fernbedienung abgeschaltet'],
            8320  => ['Standby mode enabled by remote control', 'Standby-Modus per Fernbedienung aktiviert'],
            9000  => ['Locked by anti-theft lock', 'Durch Diebstahlsicherung gesperrt'],
            10120 => ['Abnormal SPI communication', 'Anormale SPI-Kommunikation'],
            10121 => ['Over temperature protection', 'Übertemperaturschutz'],
            10122 => ['Locked by anti-theft lock', 'Durch Diebstahlsicherung gesperrt'],
            10123 => ['Standby mode enabled by remote control', 'Standby-Modus per Fernbedienung aktiviert'],
            10125 => ['Grid configuration parameter error', 'Parameterfehler bei der Konfiguration des Elektrizitätsnetzes'],
            10127 => ['Firmware error', 'Firmwarefehler'],
            10130 => ['Offline', 'Offline'],
            10131 => ['Abnormal Leakage Current', 'Anormaler Leckstrom'],
            10141 => ['Grid overvoltage', 'Netzüberspannung'],
            10142 => ['Grid overvoltage (10 min mean value)', 'Netzüberspannung (10-min. Mittelwert)'],
            10143 => ['Grid undervoltage', 'Netzunterspannung'],
            10144 => ['Grid overfrequency', 'Netzüberfrequenz'],
            10145 => ['Grid underfrequency', 'Netzunterfrequenz'],
            10146 => ['High RoCoF', 'Hohe RoCoF'],
            10147 => ['No voltage on grid port', 'Keine Spannung am Netzanschluss'],
            10148 => ['Grid disconnection', 'Netztrennung'],
            10149 => ['Island detected', 'Inselbetrieb festgestellt'],
            10152 => ['Abnormal grid phase', 'Anormale Netzphase'],
            10153 => ['Abnormal Grid Neutral Wiring', 'Anormale Netzneutralleiterverkabelung'],
            10183 => ['Abnormal Relay', 'Anormales Relais'],
            10200 => ['PV1 Reverse Connection', 'PV1-Anschlusseinstellung stornieren'],
            10201 => ['PV2 Reverse Connection', 'PV2-Anschlusseinstellung stornieren'],
            10202 => ['PV3 Reverse Connection', 'PV3-Anschlusseinstellung stornieren'],
            10203 => ['PV4 Reverse Connection', 'PV4-Anschlusseinstellung stornieren'],
            10204 => ['PV misconnection', 'PV-Fehlanschluss'],
            10205 => ['MPPT-A input overvoltage', 'Eingangsüberspannung bei MPPT-A'],
            10206 => ['MPPT-B input overvoltage', 'Eingangsüberspannung bei MPPT-B'],
            10207 => ['MPPT-A input undervoltage', 'Eingangsunterspannung bei MPPT-A'],
            10208 => ['MPPT-B input undervoltage', 'Eingangsunterspannung bei MPPT-B'],
            10209 => ['PV1 no input', 'PV1 ohne Eingang'],
            10210 => ['PV2 no input', 'PV2 ohne Eingang'],
            10211 => ['PV3 no input', 'PV3 ohne Eingang'],
            10212 => ['PV4 no input', 'PV4 ohne Eingang'],
            10213 => ['PV1 & PV2 abnormal wiring', 'Verdrahtungsfehler bei PV1 und PV2'],
            10214 => ['PV3 & PV4 abnormal wiring', 'Verdrahtungsfehler bei PV3 und PV4'],
            10215 => ['MPPT-C input overvoltage', 'Eingangsüberspannung bei MPPT-C'],
            10216 => ['MPPT-C input undervoltage', 'Eingangsunterspannung bei MPPT-C'],
            10217 => ['PV5 no input', 'PV5 ohne Eingang'],
            10218 => ['PV6 no input', 'PV6 ohne Eingang'],
            10219 => ['PV5 & PV6 abnormal wiring', 'Verdrahtungsfehler bei PV5 und PV6'],
            10220 => ['MPPT-D input overvoltage', 'Eingangsüberspannung bei MPPT-D'],
            10221 => ['MPPT-D input undervoltage', 'Eingangsunterspannung bei MPPT-D'],
            10225 => ['BoostA overvoltage protection failure', 'Fehler beim BOOSTA-Überspannungsschutz'],
            10226 => ['BoostB overvoltage protection failure', 'Fehler beim BOOSTB-Überspannungsschutz'],
            10227 => ['BoostC overvoltage protection failure', 'Fehler beim BOOSTC-Überspannungsschutz'],
            10228 => ['BoostD overvoltage protection failure', 'Fehler beim BOOSTD-Überspannungsschutz'],
            10229 => ['Bus overvoltage protection failure', 'Störung des Bus-Überspannungsschutzes'],
            10230 => ['Bus undervoltage protection failure', 'Störung des Bus-Unterspannungsschutzes'],
            10231 => ['PV1 Arcing Fault', 'PV1 Störlichtbogen'],
            10232 => ['PV2 Arcing Fault', 'PV2 Störlichtbogen'],
            10233 => ['PV3 Arcing Fault', 'PV3 Störlichtbogen'],
            10234 => ['PV4 Arcing Fault', 'PV4 Störlichtbogen'],
            10235 => ['Abnormal Arcing Self-checking Circuit', 'Anormaler Lichtbogen-Selbsttestkreis'],
            10236 => ['Abnormal Inverter Driver Circuit', 'Anormaler Wechselrichter-Treiberkreis'],
            10301 => ['Hardware Error Code 301', 'Hardwarefehlercode 301'],
            10302 => ['Hardware Error Code 302', 'Hardwarefehlercode 302'],
            10303 => ['Hardware Error Code 303', 'Hardwarefehlercode 303'],
            10304 => ['Hardware Error Code 304', 'Hardwarefehlercode 304'],
            10305 => ['Hardware Error Code 305', 'Hardwarefehlercode 305'],
            10306 => ['Hardware Error Code 306', 'Hardwarefehlercode 306'],
            10307 => ['Hardware Error Code 307', 'Hardwarefehlercode 307'],
            10308 => ['Hardware Error Code 308', 'Hardwarefehlercode 308'],
            10309 => ['Hardware Error Code 309', 'Hardwarefehlercode 309'],
            10310 => ['Hardware Error Code 310', 'Hardwarefehlercode 310'],
            10311 => ['Hardware Error Code 311', 'Hardwarefehlercode 311'],
            10315 => ['BOOSTA internal short circuit failure', 'BOOSTA interner Kurzschlussfehler'],
            10316 => ['BOOSTB internal short circuit failure', 'BOOSTB interner Kurzschlussfehler'],
            10317 => ['BOOSTC internal short circuit failure', 'BOOSTC interner Kurzschlussfehler'],
            10318 => ['BOOSTD internal short circuit failure', 'BOOSTD interner Kurzschlussfehler'],
            10319 => ['BoostA Overcurrent Protection Failure', 'Ausfall des BOOSTA-Überstromschutzes'],
            10320 => ['BoostB Overcurrent Protection Failure', 'Ausfall des BOOSTB-Überstromschutzes'],
            10321 => ['BoostC Overcurrent Protection Failure', 'Ausfall des BOOSTC-Überstromschutzes'],
            10322 => ['BoostD Overcurrent Protection Failure', 'Ausfall des BOOSTD-Überstromschutzes'],
            10323 => ['INVA overcurrent protection failure', 'INVA-Überstromschutzfehler'],
            10324 => ['INVB overcurrent protection failure', 'INVB-Überstromschutzfehler'],
            10325 => ['INVC overcurrent protection failure', 'INVC-Überstromschutzfehler'],
            10326 => ['Arcing Lock-Up', 'Sperrlichtbogen'],
        ];

        /**
         * Liefert den Klartext zu einem Warncode.
         *
         * @param int $Code
         * @param bool $German true für deutschen Text
         * @return string
         */
        public static function GetText(int $Code, bool $German): string
        {
            if (!isset(self::Texts[$Code])) {
                return ($German ? 'Unbekannter Code ' : 'Unknown code ') . $Code;
            }
            return self::Texts[$Code][$German ? 1 : 0];
        }
    }
}
